apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-dance-templates
  description: A collection of RHDH templates for Project Dance
spec:
  type: url
  targets:
     - scaffolder-templates/quarkus-insecure-jenkins-template/template.yaml
     - scaffolder-templates/quarkus-secure-jenkins-template/template.yaml
     - scaffolder-templates/quarkus-secure-tekton-template/template.yaml
